import { food } from './app/shared/models/food';
import { Tag } from './app/shared/models/tags';
export const sample_food: food[] = [
  {
    id: '1',
    name: 'vegetable pizza',
    price: 9,
    cookTime: '40-50',
    favorite: true,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/images/food/img1..avif',
    tags: ['fastfood', 'pizza', 'lunch'],
  },
  {
    id: '2',
    name: 'Mashroom pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/images/food/img1..avif',
    tags: ['fastfood', 'pizza', 'lunch'],
  },
  {
    id: '3',
    name: 'vegBurst pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/images/food/img1..avif',
    tags: ['fastfood', 'pizza', 'lunch'],
  },
  {
    id: '4',
    name: 'tangyTomato pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/images/food/img1..avif',
    tags: ['fastfood', 'pizza', 'lunch'],
  },
  {
    id: '5',
    name: 'corn pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/images/food/img1..avif',
    tags: ['fastfood', 'pizza', 'lunch'],
  },
  {
    id: '6',
    name: 'mixveg pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/images/food/img1..avif',
    tags: ['fastfood', 'pizza', 'lunch'],
  },
];

export const sample_tags: Tag[] = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
];
